language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
  - "0.8"
  - "iojs"
  - "iojs-v1.0.4" 

notifications:
    template:
      - "Build by %{author} :"
      - "Git Info: %{branch} - %{commit} with the message %{commit_message}"
      - "Travis states: %{message}"
      - "Build Details: %{build_url}"
      - "Change View: %{compare_url}"
      - "result = %{result}"
      - "elapsed time... %{duration}"
    use_notice: true
    skip_join: false

branches:
  only:
    - master
    - devel
git:
  submodules: false  
